# Generated by Django 5.0 on 2023-12-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='news/', max_length=255, null=True)),
                ('image_preview', models.ImageField(editable=False, upload_to='news/thumbnails/', max_length=255, null=True)),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'News_singular',
                'verbose_name_plural': 'News_plural',
            },
        ),
    ]
